<a href="https://colab.research.google.com/github/enimyreddykrishna/krishna-reddy/blob/main/python_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.How do you import the NumPy library using an alias?

In [1]:
import numpy as np

arr = np.array([10, 20, 30])
print(arr)


[10 20 30]


How do you check the version and configuration of NumPy?

In [5]:

print(np.__version__)


2.0.2


In [7]:
print(np.__config__)

<module 'numpy.__config__' from '/usr/local/lib/python3.12/dist-packages/numpy/__config__.py'>


How do you create a vector filled with zeros of size 10?

In [8]:
import numpy as np

zeros_vector = np.zeros(10)
print(zeros_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


How do you find help/documentation for a NumPy function from the command line?

In [9]:
import numpy as np
help(np.array)


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

.How do you create a zero vector of size 10 with the fifth element as 1?

In [10]:
import numpy as np
vector = np.zeros(10)
vector[4] = 1

print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


How do you create a vector with values from 10 to 49?

In [11]:
import numpy as np
vector=np.arange(10,50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


How do you reverse a vector?

In [12]:
vector=np.arange(10,50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


How do you create a 3x3 matrix with values from 0 to 8?

In [13]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


How do you find indices of non-zero elements in an array?

In [14]:
import numpy as np

array = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(array)
print(indices)


(array([0, 2, 4, 6]),)


How do you create a 3x3 identity matrix?

In [15]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 11.How do you generate a 3x3x3 array with random values?


In [16]:
array=np.random.rand(3,3,3)
print(array)

[[[0.47836843 0.40457834 0.58067117]
  [0.22344274 0.57986634 0.49390261]
  [0.15357957 0.32420924 0.81342308]]

 [[0.04363695 0.35711886 0.3959895 ]
  [0.35518487 0.37403624 0.47544174]
  [0.77928651 0.06345889 0.00149244]]

 [[0.40812532 0.3628364  0.69388534]
  [0.69393157 0.88093211 0.13525949]
  [0.66083885 0.50167403 0.97452955]]]


 12.How do you find the min and max values in a 10x10 random matrix?

In [19]:
matrix = np.random.rand(10,10)
min_value =np.min(matrix)
max_value= np.max(matrix)
print(min_value)
print(max_value)

0.000732758170843506
0.9974892204668514


How do you calculate the mean of a random vector of size 30?

In [21]:
random = np.random.rand(30)
mean = np.mean(random)
print(mean)

0.6091161675743147


How do you create a 2D array with 1s on the border and 0s inside?

In [2]:
import numpy as np

array = np.ones((5, 5), dtype=int)
array[1:-1, 1:-1] = 0
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.

In [3]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


 16.How do you create a matrix with values below the diagonal?